// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	network "gitub.com/sriramr98/go_kvdb/core/network"
)

// Dialer is an autogenerated mock type for the Dialer type
type Dialer struct {
	mock.Mock
}

// Dial provides a mock function with given fields: _a0, address
func (_m *Dialer) Dial(_a0 string, address string) (network.Conn, error) {
	ret := _m.Called(_a0, address)

	var r0 network.Conn
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (network.Conn, error)); ok {
		return rf(_a0, address)
	}
	if rf, ok := ret.Get(0).(func(string, string) network.Conn); ok {
		r0 = rf(_a0, address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(network.Conn)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewDialer interface {
	mock.TestingT
	Cleanup(func())
}

// NewDialer creates a new instance of Dialer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDialer(t mockConstructorTestingTNewDialer) *Dialer {
	mock := &Dialer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
