name: Run all Tests

on:
  pull_request:
    paths:
      - '**/*.go'
    branches:
      - dev
      - master


jobs:
  test:
    runs-on: 1.20.x

    steps:
      - name: Install go
        uses: actions/setup-go@v4

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Test Go
        run: go test ./...
